In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
# Data type of each element in list_
print("Data type of elements in list_:")
for i in list_:
    print(type(i))

# Data type of each element in array_list
print("Data type of elements in array_list:")
for i in array_list:
    print(type(i))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
array_list = np.array(object=list_, dtype=int)

# Data type of each element in list_
print("Data type of elements in list_:")
for i in list_:
    print(type(i))

# Data type of each element in array_list after conversion
print("Data type of elements in array_list:")
for i in array_list:
    print(type(i))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [4]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
